### PR TITLE
attempt to make it work with arrays

### PR DESCRIPTION
**Pull request by caub**
cf #15

### CODE REVIEW

**Comment by caub** [comment]
unfortunately I get a maximum call stack stack error

```
> d=require('./diff')
[Function: diff] { INSERT: 1, DELETE: -1, EQUAL: 0 }
> d(['a','c'], ['a','s','c'])
Uncaught RangeError: Maximum call stack size exceeded
    at diff_bisectSplit_ (/home/caub/dev/fast-diff/diff.js:280:22)
    at diff_bisect_ (/home/caub/dev/fast-diff/diff.js:219:20)
    at diff_compute_ (/home/caub/dev/fast-diff/diff.js:147:10)
    at diff_main (/home/caub/dev/fast-diff/diff.js:74:15)
    at diff_bisectSplit_ (/home/caub/dev/fast-diff/diff.js:286:15)
    at diff_bisect_ (/home/caub/dev/fast-diff/diff.js:219:20)
    at diff_compute_ (/home/caub/dev/fast-diff/diff.js:147:10)
    at diff_main (/home/caub/dev/fast-diff/diff.js:74:15)
    at diff_bisectSplit_ (/home/caub/dev/fast-diff/diff.js:286:15)
    at diff_bisect_ (/home/caub/dev/fast-diff/diff.js:219:20)
> 
```

**Comment by make-github-pseudonymous-again** [comment]
Hi @caub!

One thing you may have to look for is that somewhere in the code there is a *longest common prefix* subroutine that uses an algorithm hinted at here: https://neil.fraser.name/news/2007/10/09. While `string1 === string2` works as intended, `array1 === array2` will not work. I do not think the output will be correct in general and you may hit an infinite recursion depending on how the base case is handled (either in the longest common prefix procedure or in the Hirschberg divide-and-conquer scheme). Also, I am not sure the speed-up obtained for strings when using string `substring/slice` can be extended to `Array` slices.

A second thing, did you check [the differences between `substring` and `slice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring#differences_between_substring_and_slice)?

Maybe someone who wrote this library could chime in to confirm/infirm my worries?

**Comment by make-github-pseudonymous-again** [comment]
PS: the solution to the first problem is to implement the longest common prefix subroutine as a linear scan when handling arrays.

**Comment by caub** [comment]
Oh, good points, thanks for the help, I'll try to compare arrays using `Array.from({length: Math.max(a1.length, a2.length)}).some((_, i) => a1[i] === a2[i])` or even just stringify arrays and compare the 2 strings

I've also found https://github.com/YuJianrong/fast-array-diff to work well with both arrays and strings

**Comment by make-github-pseudonymous-again** [comment]
@caub This implementation also looks like it handles arrays: https://github.com/gliese1337/fast-myers-diff

**Pull request closed without merging**
